'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDownToLine, ArrowUpFromLine, ArrowUpRight, File, Laptop, RefreshCw, ShieldCheck, Timer, Upload } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { Empty, EmptyTitle, EmptyDescription } from '@/components/ui/empty';

type Item={id:string;name:string;size:number;created:number;expires:number};
const size=(n:number)=>n<1000000?`${(n/1000).toFixed(1)} KB`:`${(n/1000000).toFixed(1)} MB`;
export default function Home(){
 const [files,setFiles]=useState<Item[]>([]),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(0),[drag,setDrag]=useState(false),[note,setNote]=useState('');const input=useRef<HTMLInputElement>(null);
 async function refresh(){try{const r=await fetch('/api/files',{cache:'no-store'});if(!r.ok)throw Error('暂时无法同步，请稍后重试');const data=await r.json() as {files:Item[]};setFiles(data.files);setLoaded(true);setError('');}catch(e){setError((e as Error).message)}}
 useEffect(()=>{refresh();const t=setInterval(refresh,5000);return()=>clearInterval(t)},[]);
 async function upload(list:FileList|null){if(!list||busy)return;setBusy(true);setError('');setNote('');let done=0;try{for(const file of Array.from(list)){if(file.size>100000000)throw Error('单个文件不能超过 100 MB');setNote(`正在上传 ${file.name}`);await new Promise<void>((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST','/api/files?name='+encodeURIComponent(file.name));x.setRequestHeader('Content-Type','application/octet-stream');x.setRequestHeader('X-File-Size',String(file.size));x.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(e.loaded/e.total*100))};x.onload=()=>{if(x.status>=200&&x.status<300)resolve();else {try{reject(Error(JSON.parse(x.responseText).error))}catch{reject(Error('上传失败，请重试'))}}};x.onerror=()=>reject(Error('网络中断，请重新上传'));x.send(file)});done++;await refresh();}setNote(`${done} 个文件已就绪，可以在另一台电脑下载`);}catch(e){setError((e as Error).message)}finally{setBusy(false);setProgress(0);if(input.current)input.current.value=''}}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'list_transfer_files',description:'Refresh the available temporary files and return their download paths.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No input fields are accepted');const r=await fetch('/api/files',{cache:'no-store'});if(!r.ok)throw Error('Unable to load files');const data=await r.json() as {files:Item[]};setFiles(data.files);setLoaded(true);return {files:data.files.map((f:Item)=>({...f,downloadPath:'/api/files/'+f.id}))}}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 const used=files.reduce((n,f)=>n+f.size,0);
 return <div className="shell"><header><a className="brand" href="/"><span className="brand-icon"><ArrowUpFromLine size={19}/><ArrowDownToLine size={19}/></span>Drop Bridge<span className="brand-cn">文件中转站</span></a><span className="private"><ShieldCheck size={16}/>个人空间</span></header><main><div className="heading"><div><p className="eyebrow">你的设备之间，一站中转</p><h1>文件，换台电脑接着用<span>。</span></h1><p className="intro">在这里放下，在另一台电脑取走。</p></div><div className="device"><Laptop size={22}/><span>跨设备同步<br/><small>打开同一个网址即可</small></span></div></div><section className={'drop '+(drag?'drag':'')} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);upload(e.dataTransfer.files)}}><div className="upload-mark"><Upload size={32} strokeWidth={1.5}/></div><h2>{busy?'正在把文件送到中转站':'把文件拖到这里'}</h2><p>文档、图片、视频，或任何你需要的资料</p><button className="primary" disabled={busy} onClick={()=>input.current?.click()}><Upload size={17}/>{busy?'上传中…':'选择文件'}<ArrowUpRight size={17}/></button><input ref={input} type="file" multiple hidden onChange={e=>upload(e.target.files)}/><span className="drop-meta">支持多个文件 · 总容量 100 MB</span>{busy&&<Progress aria-label="上传进度" className="upload-progress" value={progress}/>}</section><div role="status" className="feedback">{note}</div>{error&&<div role="alert" className="error">{error} <button onClick={refresh}>重新同步</button></div>}<section className="file-section"><div className="section-heading"><h2>待取文件 <span>{files.length}</span></h2><button className="refresh" onClick={refresh}><RefreshCw size={15}/>刷新</button></div><div className="file-list">{!files.length?<Empty className="empty"><File size={29} strokeWidth={1.3}/><EmptyTitle>{loaded?'中转站现在是空的':'正在连接中转站…'}</EmptyTitle><EmptyDescription>上传后，文件会出现在这里。</EmptyDescription></Empty>:files.map(f=><div className="file-row" key={f.id}><div className="file-icon"><File size={22}/></div><div className="file-info"><strong>{f.name}</strong><span>{size(f.size)} · {new Date(f.created).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})} 上传</span></div><a className="download" href={'/api/files/'+f.id} download={f.name}><ArrowDownToLine size={18}/><span>下载</span></a></div>)}</div></section><footer><div className="capacity"><span>临时空间 <strong>{size(used)} / 100 MB</strong></span><Progress value={Math.min(100,used/1000000)} aria-label="空间使用量"/></div><div className="retention"><Timer size={18}/><span>每日 08:00 到期<small>北京时间 · 到期不可下载，访问时清除文件</small></span></div></footer><p className="bottom-note">在另一台电脑使用同一账号打开本站，点击文件旁的下载按钮。</p></main></div>
}
